### PR TITLE
Normalize install_path before creating dir

### LINKED ISSUE #592: `install_path` parameter breaks in WINDOWS subprocesses
When running the `covr` in the `callr` subprocess on Windows, `covr::package_coverage` unexpectedly breaks if `install_path` has double backslashes (valid WINDOWS path) `\\` instead of the single forward slashes `/`. That's due to the path normalization which happens after creating the directory: 

https://github.com/r-lib/covr/blob/ca4241da03a30b76a8d8cbfc194371cb94ca512e/R/covr.R#L413-L415

Swapping these two lines will make the internal `normalize_path` function first replace all the `\\` with `/` so the function can proceed as expected. I'm not sure why exactly this is an issue in a subprocess, but the change looks reasonable either way.

### PR DESCRIPTION
**Pull request by maksymiuks**
Closes #592 

Candidate fix to the issue reported on Windows machines.

### CODE REVIEW

File: R/covr.R [hunk 1]
```diff
@@ -410,9 +410,8 @@ package_coverage <- function(path = ".",
     root <- NULL
   }
 
-  dir.create(install_path)
   # tools::testInstalledPackage requires normalized install_path (#517)
-  install_path <- normalize_path(install_path)
+  dir.create(install_path <- normalize_path(install_path))
```
Comment (jimhester) [inline R/covr.R:414]:
```suggestion
  install_path <- normalize_path(install_path)
  dir.create(install_path)
```

File: NEWS.md [hunk 2]
```diff
@@ -15,6 +15,10 @@
 
 * Added support for `klmr/box` modules. This works best with `file_coverage()`. (@radbasa, #491)
 
+* Normalize `install_path` path before creating directory to prevent
+  failures when during running covr in subprocess a path with Windows 
+  `\\` file path separator is provided. (@maksymiuks, #592)
```
Comment (jimhester) [inline NEWS.md:20]:
```suggestion
* Normalize `install_path` path before creating directory to prevent
  failures when running covr in a subprocess using a path with Windows 
  `\\` path separators. (@maksymiuks, #592)
```

**Review by jimhester — CHANGES_REQUESTED** [review]
Thanks, made a couple of suggested edits, otherwise looks good.

**Comment by maksymiuks** [comment]
Thanks for the review, I've applied your suggestions :)

**Review by jimhester — APPROVED** [review]

**Comment by jimhester** [comment]
Thanks!
